### ISSUE TITLE
How to get a tree of dimension values with less than n queries

### ISSUE THREAD

**Issue by ptbrowne** [zazuko/cube-hierarchy-query#7]
The usecase of visualize is to show the whole tree of values with parents and children for a particular cube.

Currently in the children example, only the children for one parent at a time is queried. In the context of the bathing sites + monitoring programme (bathing site dataset), we have 26 monitoring programmes, so 26 queries. It takes 9s to fetch the dimension values. You can reproduce by running the children example on the bathing water dataset:

```
yarn example ./examples/children.ts --cube https://environment.ld.admin.ch/foen/ubd0104/8 list-values 
```

(this uses the CLI args feature from my branch in #4 ).

 In my mind it would be better if in 1 query we could query a value tree for a dimension (upper level).

```
const tree = await fetchTreeDimensionValues(dimensionIri, { parentDepth: 1 }) // Ideally only 1 or 2 SPARQL queries should be done
```

We have done in visualize a custom implementation of the hierarchy fetching but it misses some feature like the inversePath support.

Do you think this feature could be implemented in cube-hierarchy-query ?

**Comment by tpluscode** [comment]
So you are asking for a way to retrieve the entire hierarchy in one go? I'm curious why it's necessary to fetch everything at once for all hierarchy roots. And deeply. 

Should be possible but for large dimensions this can mean a lot of data. Think cantons+district+municipalities

**Comment by ptbrowne** [comment]
The primary goal of the hierarchies inside visualize is to show the children grouped by their parent. For example in the bottom right panel here:

<img width="565" alt="image" src="https://user-images.githubusercontent.com/465582/177742084-d4e9ac4d-0c87-4239-a942-dce021aae1f0.png">

The children here being bathing site and the parent monitoring programmes.

What we need is a way to query the parent for all the children values that are present in the dataset.

**Comment by tpluscode** [comment]
@ptbrowne I look at the query currently generated for children at a given level. tl;dr; it looks like this:

```sparql
PREFIX schema: <http://schema.org/>

DESCRIBE <http://example.com/Affoltern> ?this
WHERE {
  <http://example.com/Affoltern> schema:containsPlace ?this .
  
  VALUES ?parent4 { <http://example.com/Europe> }
  ?parent4 ^schema:containedInPlace ?parent3 .
  ?parent3 ^schema:containedInPlace ?parent2 .
  ?parent2 ^schema:containedInPlace ?parent1 .
  ?parent1 schema:containsPlace ?this .

  filter (isiri(?this))
}
```

The core is to traverse the levels. In this case `?parent4` is the root (continent), and it goes down to district level. The first pattern narrows down the search only to districts of `Affoltern`. What's important, the level is also an input to this query because the path is constructed bottom-up. That's why the parent variable with highest number is the root. It is also important because, IIRC, a level can have multiple children but only one parent. 

It should be very easy to reuse the overall structure of this query to find all parents of specific leafs.

```sparql
PREFIX schema: <http://schema.org/>

# Just get all triples
DESCRIBE *
WHERE {
  # No parent restriction
  # <http://example.com/Affoltern> schema:containsPlace ?this .
  
  # Path as previously
  VALUES ?parent4 { <http://example.com/Europe> }
  ?parent4 ^schema:containedInPlace ?parent3 .
  ?parent3 ^schema:containedInPlace ?parent2 .
  ?parent2 ^schema:containedInPlace ?parent1 .
  ?parent1 schema:containsPlace ?this .
  
  # Filter by the leafs
  filter(?this IN (<http://example.com/Bonstetten>, <http://example.com/Nidau>))
}
```

The hierarchy level would still need to be an input, I think

What I tried to point out when we talked is that a query like that assumes that the calling code will know at which level the given resources (Bonstetten, Nidau) are in the hierarchy. Otherwise we might need to add an alternative of similar `IN` filter at every level to accommodate for the values being at any one of them.

**Comment by tpluscode** [comment]
As for the result, I think I would wrap the dataset in a simpler API to go from roots down, as you would construct a tree in the UI.

```ts
class Branch {
  pointer: GraphPointer
  // dynamically retrieved from graph by following `meta:nextInHierarchy`
  get children(): Branch[]
}

interface HierarchyTree {
  roots: Branch[]
}

declare async function getHierarchy(leafLevel: GraphPointer, ...leafs: NamedNode[]): HierarchyTree

let municipalityLevel
const leafs = [
  namedNode('Bonstetten'),
  namedNode('Nidau'),
]
const { roots } = await getHierarchy(municipalityLevel, ...leafs)

// iterate roots and recursively render branches 
```

**Comment by ptbrowne** [comment]
Sorry, I had missed this reply. Yep, having the result with an easier API to get the children would be very appreciable. Maybe `Node` instead of Branch ?

Following our latest discussion, the leafs attribute would not be necessary here right ?

**Comment by tpluscode** [comment]
Not at this point, since we agreed to load the whole hierarchy in one go

I'll share a draft PR today

**Comment by ptbrowne** [comment]
Fixed now, thanks @tpluscode !
