### ISSUE TITLE
Problem retrieving the tree of values for Öffentliche ausgaben ?

### ISSUE THREAD

**Issue by ptbrowne** [zazuko/cube-hierarchy-query#8]
Hi,

It seems to me that with the children example, the hierarchy for Öffentliche ausgaben is not correctly retrieved.

```
$ yarn example ./examples/children.ts --cube https://environment.ld.admin.ch/foen/fab_Offentliche_Ausgaben_test3/7 list-values
{
  "b1_genid2d7c6d03ed5794414faeda2dc4519fbb002d49599B50A93CE18A8B372AFB009FD3F4": {
    "name": "COFOG Hierarchy Level 2",
    "iri": "b1_genid2d7c6d03ed5794414faeda2dc4519fbb002d49599B50A93CE18A8B372AFB009FD3F4",
    "children": {
      "https://ld.admin.ch/cube/dimension/cofog/gftot": [
        {
          "iri": "https://ld.admin.ch/cube/dimension/cofog/gftot",
          "children": [
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf06"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf04"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf01"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf08"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf09"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf02"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf05"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf07"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf03"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf10"
            }
          ]
        },
        {
          "iri": "https://ld.admin.ch/cube/dimension/cofog/gftot",
          "children": [
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf06"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf04"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf01"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf08"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf09"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf02"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf05"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf07"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf03"
            },
            {
              "value": "https://ld.admin.ch/cube/dimension/cofog/gf10"
            }
          ]
        }
      ]
    }
  },
  "b1_genid2d7c6d03ed5794414faeda2dc4519fbb002d82B5426C54937CC63AB608B122ED8DBC": {
    "name": "COFOG Hierarchy Level 3",
    "iri": "b1_genid2d7c6d03ed5794414faeda2dc4519fbb002d82B5426C54937CC63AB608B122ED8DBC",
    "children": {
      "https://ld.admin.ch/cube/dimension/cofog/gftot": [
        {
          "iri": "https://ld.admin.ch/cube/dimension/cofog/gftot",
          "children": []
        },
        {
          "iri": "https://ld.admin.ch/cube/dimension/cofog/gftot",
          "children": []
        }
      ]
    }
  }
}
```

- I think we should have much more values.
- I do not see the labels
- I wonder why there are duplicates of gftot in the last level

Can we discuss this case when you have time @tpluscode ?

Thanks

**Comment by tpluscode** [comment]
First, looks like the example code to go into the child levels is not correct. Here's a diff of the inner `SELECT` query

```diff
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX schema: <http://schema.org/>

SELECT DISTINCT ?this WHERE {
-  <https://ld.admin.ch/cube/dimension/cofog/gf06> ^skos:broader ?this .
+  <https://ld.admin.ch/cube/dimension/cofog/gftot> ^skos:broader ?this .

  VALUES ?parent2 { <https://ld.admin.ch/cube/dimension/cofog/gftot> }
  ?parent2 ^skos:broader ?parent1 .
  ?parent1 ^skos:broader ?this .

  filter (isiri(?this))
  OPTIONAL { ?this schema:name ?order0 }
}
ORDER BY ?order0
LIMIT 100 OFFSET 0
```

See that rather than expanding the children of the Nth level (here `.../gf06`), the query re-uses the root IRI. That would be [this line](https://github.com/zazuko/cube-hierarchy-query/blob/master/examples/children.ts#L73). There you should replace that argument with values from the `children` queries for any given level and drill into that

**Comment by ptbrowne** [comment]
Seeing this was in the original example code, and if you have a clear idea of what to fix, could you fix the example 😊 ? Seeing that this query can be difficult to build, I think it should be outside of the examples and directly in the library, what do you think ?

**Comment by tpluscode** [comment]
The duplication comes already from the `rdf-cube-view-query` library. If you inspect the cube dataset you will find that the property with `sh:path <https://environment.ld.admin.ch/foen/fab_Offentliche_Ausgaben_test3/code>` appears twice. Hence, when you select `.has(meta.inHierarchy).out(meta.inHierarchy)` you get two duplicates of same hierarchy

The cube in Lindas https://s.zazuko.com/fe1dza is correct

**Comment by tpluscode** [comment]
> and if you have a clear idea of what to fix, could you fix the example

Well, you will probably need to extract the loop itself into a recursive function. In first iteration you have root level and hierarchy roots. One every subsequent call you have the `nextInHierarchy` level and children from the previous iteration. And probably `Array#reduce` since you build up that tree in JS. In pseudo, ignoring async/await, something like

```js
function listHierarchicalLevels() {
 return roots.reduce(getChildren(level, options), {})
}

function getChildren (level, options) {
  return (res, parent) => {
    const { parent, children: childrenPointers } = children(level, parent, options)

    // construct the result object for current level/parent
    let currentResult

    const nextLevel = hierarchy.out(meta.nextInHierarchy).toArray().shift()
    if (nextLevel) {
      // recurse here into deeper levels
      return childrenPointers.reduce(nextLevel, options), { ...res, ...currentResult })
    }
 
    return { ...res, ...currentResult }
  }
}
```

> Seeing that this query can be difficult to build, I think it should be outside of the examples and directly in the library, what do you think ?

Cue https://github.com/zazuko/cube-hierarchy-query/issues/7#issuecomment-1177687263
If I understood you correctly, getting all children of all levels is an anti-goal here. What you needed was to go up, from leafs to their respective roots.

**Comment by tpluscode** [comment]
Here's a rendition of that linked query which would retrieve only paths from the level 2 children `<https://ld.admin.ch/cube/dimension/cofog/gf0606>` and `<https://ld.admin.ch/cube/dimension/cofog/gf0701>`: https://s.zazuko.com/3QBxSM

Here's the result without unnecessary duplication:
https://s.zazuko.com/d8HAfq

Please remember what I tried to say in our last conversation. The assumption would have to be that the leafs filtered are indeed at the bottom of a given hierarchy. Otherwise this needs slight rethinking

**Comment by ptbrowne** [comment]
Fixed now
